### ISSUE TITLE
How to use for multiple continuous blocks of data ?

### ISSUE THREAD

**Issue by ventosus** [vnmakarov/mum-hash#13]
In how to use MUM we can read:

* mum_hash_init, mum_hash_step, and mum_hash_finish for hashing complex data structures
* mum_hash64 for hashing a 64-bit data
* mum_hash for hashing any continuous block of data

The most often scenario I'm woking with is creating hashes for multiple continuous blocks of data.
How should I do that with MUM, it is not obvious from the source.

e.g. how to I get the single hash over the following arrays with the right combinations of mum functions ?

    const uint8_t key_1 [1] = { 0 };
    const uint8_t key_2 [2] = { 1, 2 };
    const uint8_t key_3 [3] = { 1, 2, 3 };

**Comment by vnmakarov** [comment]
You can use mum_hash instead of mum_hash_step.  For example, if you have 3 long arrays a1,a2, and a3, instead of using numerous hash_step you can use the following code:
```
h =  mum_hash_init (42);
h = mum_hash (a1, sizeof (a1), h);
h = mum_hash (a2, sizeof (a2), h);
h = mum_hash (a3, sizeof (a3), h);
h = mum_hash_finish (h);
```
In this sequence for smaller data represented by 64-bit int you still can use mum_hash_step.

**Comment by ventosus** [comment]
@vnmakarov awesome, thanks, exactly what I was looking for.
