### ISSUE TITLE
Compilation warnings with gcc

### ISSUE THREAD

**Issue by a16bitsysop** [vnmakarov/mum-hash#15]
When compiling with the -wno-unused-value flag the following warning is produced:

```
mum.h:118:13: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  118 |   lo = v * p, hi;
      |
```

**Comment by vnmakarov** [comment]
Thank you very much for reporting this. It seems a typo which makes mum hash wrong for aarch64.  I guess initially it was a declaration, not a statement.

I fixed it https://github.com/vnmakarov/mum-hash/commit/322fdd931c6e61c463e04ce5f37cab4918c4d2d6#diff-58cc585617c05bdc7075c67e5fc222c3af5db6d8bdef9b8a2f2a81176e40eeb6.

**Comment by a16bitsysop** [comment]
Thanks, that fixes it.
